kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: banking-kind
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      - containerPort: 30400
        hostPort: 30400
        protocol: TCP
